name: pytest
on: [push, pull_request]
jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: 
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [ 3.9, "3.10", 3.11]
    steps:
    - uses: actions/checkout@master

    - name: Setup Python  
      uses: actions/setup-python@master
      with:
        python-version: ${{ matrix.python-version }}

    - name: Static code checking with pyflakes
      run: |
        pip install pyflakes
        pyflakes mkdocs_table_reader_plugin

    - name: Run unit tests
      run: |
        pip install -r tests/test_requirements.txt
        pip install -e .
        pytest --cov=mkdocs_table_reader_plugin --cov-report=xml
      
